elasticsearch:
  home: C:\Program Files\Elastic\Elasticsearch
  cluster:
    name: socnet
server:
  port: 8084

spring:
  application:
    name: elastic
#start elasticsearch with this script :
#elasticsearch -E cluster.name=socnet -E node.name=socnet_node