server:
  port: 8084

spring:
  application:
    name: elastic
  rabbitmq:
    host: 172.17.0.1
    port: 5673
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: posts
      default:
       contentType: application/json    

elastic:
  host: 172.17.0.1
  port: 9200
