spring:
  application:
    name: gateway

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8082/eureka/
    register-with-eureka: true
    fetch-registry: true
    region: default
    registry-fetch-interval-seconds: 5

zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    social:
      path: /social/**
    file-service:
      path: /file-service/**

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000