server:
  port: 8082

spring:
  application:
    name: social
  datasource:
    url: jdbc:mysql://172.17.0.1:6603/socnet_java_training_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  rabbitmq:
    host: 172.17.0.1
    port: 5673
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: posts
      default:
       contentType: application/json

eldest:
  date:
    year: 1950

authentication:
  jwt:
    secret:       secret
    issuer:       http://com.example.org
    audience:     http://com.example.org
    clockSkew:    10   # seconds
    validFor:     864000000 # seconds
    refreshLimit: 1    # times
    claimNames:
      authorities:  authorities
      refreshCount: refreshCount
      refreshLimit: refreshLimit